spring:

  application:
    name: spring-shop

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?createDatabaseIfNotExist=true
    username: root
    password: root

  mvc:
    format:
      date: iso
      date-time: iso

  thymeleaf:
    cache: false

  jpa:
    properties:
      hibernate:
        format_sql: true


    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

#server.port: 8081

logging:
  level:
    root: info
  #    com.vitali.entities: warn
  file:
    name: shop.log
    path: /


  logback:
    rollingpolicy:
      max-history: 1

app:
  image:
    bucket: "C:\\Work\\IdeaProjects\\spring-shop\\src\\main\\resources\\static\\images"
